goaway/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Home
    path('', views.home, name='home'),

    # Trips
    path('trips/', views.trip_index, name='trip_index'),
    path('trips/create/', views.TripCreate.as_view(), name='trip_create'),
    path('trips/<int:pk>/delete/', views.TripDelete.as_view(), name='trip_delete'),
    path('trips/<int:trip_id>/', views.trip_detail, name='trip_detail'),

    #  Days
    path('days/create/<int:trip_id>', views.days_create, name='days_create'),
    path('days/populate/<int:trip_id>', views.days_populate, name='days_populate' ),
    path('days/<int:pk>/update/', views.DayUpdate.as_view(), name='day_update'),
    path('days/<int:day_id>/', views.day_detail, name='day_detail'),

    # Activities
    path('days/<int:day_id>/activity_create', views.activity_create, name='activity_create'),
    path('activity/<int:pk>/update', views.ActivityUpdate.as_view(), name='activity_update'),
    path('days/<int:day_id>/delete/<int:activity_id>/', views.activity_delete, name='activity_delete'),
    path('activity/<int:activity_id>', views.activity_detail, name='activity_detail'),
    
    # Auth
    path('accounts/signup/', views.signup, name='signup'),

    # Photos
    path('trips/<int:trip_id>/add_photo', views.add_photo, name='add_photo')
    
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
from django import forms


# Create your models here.

TRANSPORT = (
    ('W', 'Walk'),
    ('B', 'Bike'),
    ('D', 'Drive'),
    ('T', 'Train'),
    ('F', 'Fly')
)

TIMES = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)

INOUT = (
    ('I', 'Inside'),
    ('O', 'Outside')
)

class Activity(models.Model):
    name = models.CharField(max_length=50)
    time = models.TimeField()
    inout = models.CharField(
        max_length = 1,
        choices = INOUT,
        default = INOUT[0][0]
    )
    description = models.CharField(max_length=125)

    class Meta:
        ordering = ['time']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('day', kwargs={'activity_id': self.id})
    

class Trip(models.Model):
    name = models.CharField(max_length=50)
    start = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Trip to {self.name} on {self.start}'
    
    def get_absolute_url(self):
        return reverse('days_create', kwargs={'trip_id': self.id})
    

class Day(models.Model):
    number = models.IntegerField()  
    date = models.DateField(default='')
    city = models.CharField(max_length=50, default='')
    state = models.CharField(max_length=50, default='', blank=True)
    country = models.CharField(max_length=50, default='')
    transport = models.CharField(
        max_length=1,
        choices = TRANSPORT,
        default = TRANSPORT[2][0],
        blank=True
    )
    lodging = models.CharField(max_length=50, default='')
    address = models.CharField(max_length=70, default='', blank=True)
    flight = models.CharField(max_length=20, default='', blank=True)
    activities = models.ManyToManyField(Activity, blank=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'Day {self.number} of {self.trip}'
    
    def as_dict(self):
        return {
            'number' : self.number,
            'date' : self.date
            # 'city' : self.city,
            # 'state' : self.state,
            # 'country' : self.country,
            # 'transport' : self.transport,
            # 'lodging' : self.lodging,
            # 'trip' : self.trip.id
        }
    def get_absolute_url(self):
        return reverse('day_detail', kwargs={'day_id': self.id})
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for Trip: {self.trip_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Day, Activity, Trip
from django import forms

class DayForm(ModelForm):
    class Meta:
        model = Day
        fields = '__all__'

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = ['name', 'time', 'description', 'inout']
        widgets = {
            'time': forms.widgets.DateInput(attrs={'type': 'time'})
        }
        labels = {
                'inout': 'Inside/Outside',
        }
        
# class TripForm(ModelForm):
#     class Meta:
#         model = Trip
#         fields = ['name', 'start']
#         widgets = {
#             'start': forms.widgets.DateInput(attrs={'type': 'date'})
#         }

main_app/views.py
from django.shortcuts import render, redirect
from .models import Trip, Day, Activity, Photo
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import DayForm, ActivityForm
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import timedelta, datetime
from django import forms
import uuid
import boto3
from django.conf import settings
import requests

AWS_ACCESS_KEY = settings.AWS_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = settings.AWS_SECRET_ACCESS_KEY
S3_BUCKET = settings.S3_BUCKET
S3_BASE_URL = settings.S3_BASE_URL

# Create your views here.

def home(request):
    return render(request, 'home.html')

@login_required
def trip_index(request):
    trips  = Trip.objects.filter(user=request.user)
    return render(request, 'trips/index.html', {'trips': trips})

@login_required
def trip_detail(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    days = Day.objects.filter(trip_id=trip_id)
    date_now = datetime.now().date()
    print(days)
    # res = []
    # for day in days:
    #     if day.city:
    #         response = requests.get(f'http://api.weatherapi.com/v1/forecast.json?key=9da560b0b23b45e4a16160600230604&q={day.city}&days=1&aqi=no&alerts=no')
    #         weather = response.json()
    #         res.append(weather)
    #     else:
    #         res.append('')
    # print(res)
    return render(request, 'trips/detail.html', { 'trip': trip, 'date_now': date_now})

class TripCreate(LoginRequiredMixin, CreateView):
    model = Trip
    fields = ['name', 'start']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_form(self):  
        form = super(TripCreate, self).get_form()
        form.fields['start'].widget = forms.DateInput(attrs={'type': 'date'})
        return form 
    
class TripDelete(LoginRequiredMixin, DeleteView):
    model = Trip
    success_url = '/trips/'

@login_required
def day_detail(request, day_id):
    day = Day.objects.get(id=day_id)
    activity_form = ActivityForm()
    # This makes a request to the weather api for the forecast on the day.
    date_now = datetime.now().date()
    # print(day.date)
    # print(date_now)
    if day.city:
        # if date is passed, do not call the api
        if day.date < date_now:
            weatherinfo = ''
            weather_icon = ''
        else:
        # if the date is more than 14 days, get future info:
            if day.date > date_now + timedelta(days=14):
                res = requests.get(f'http://api.weatherapi.com/v1/future.json?key=9da560b0b23b45e4a16160600230604&q={ day.city } {day.country}&dt={day.date}')
                weather = res.json()
                weatherinfo = weather['forecast']['forecastday'][0]['day']
                weather_icon = ''
                # print(weatherinfo)
            # if the date is between today and 14 days from today, get forecast plus icon:
            elif day.date <= date_now + timedelta(days=14):
                res = requests.get(f'http://api.weatherapi.com/v1/forecast.json?key=9da560b0b23b45e4a16160600230604&q={ day.city } {day.country}&dt={day.date}')
                weather = res.json()
                weatherinfo = weather['forecast']['forecastday'][0]['day']
                weather_icon = weather['forecast']['forecastday'][0]['day']['condition']['icon']
                print(weather_icon)
                # print(weatherf)
            # if the date is today get current weather:
            # elif day.date == date_now:
            #     res = requests.get(f'http://api.weatherapi.com/v1/.json?key=9da560b0b23b45e4a16160600230604&q={ day.city} { day.country}&aqi=no')
            #     weather = res.json()
            #     # print(weatherf)
            #     weatherf = weather['current']['temp_f']
            #     weather_icon = ['current']['condition']['icon']
            else:
                weatherinfo = ''
                weather_icon = ''
    else:
        weatherinfo = ''
        weather_icon = ''
    # print(res)
    # weather = res.json()
    # print(weather2)
    return render(request, 'days/detail.html', { 'day': day, 'activity_form': activity_form, 'weather': weatherinfo, 'icon': weather_icon} )

@login_required
def days_create(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    return render(request, 'days/create.html', {'trip': trip})


# This function will take the input of number of days and create that number of day objects.
# It will auto populate day.number and day.date.
@login_required
def days_populate(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    # print('This is the trip: ', trip)
    day_num = int(request.POST['day_num'])
    # print('THIS IS THE NUMBER:', day_num)
    for i in range(day_num):
        day = DayForm()
        new_day = day.save(commit=False)
        new_day.number = (i + 1)
        new_day.date = trip.start
        if i > 0:
            new_day.date += timedelta(days=i)
        new_day.trip_id = trip_id
        # print('THIS IS THE DAY: ', new_day.as_dict())
        new_day.save()
    return redirect('trip_detail', trip_id=trip_id)

class DayUpdate(LoginRequiredMixin, UpdateView):
    model = Day
    fields = ['city', 'state', 'country', 'transport', 'lodging', 'address', 'flight']

@login_required
def activity_create(request, day_id):
    form = ActivityForm(request.POST)
    new_activity = form.save(commit=False)
    new_activity.save()
    Day.objects.get(id=day_id).activities.add(new_activity.id)
    return redirect('day_detail', day_id=day_id)

@login_required
def activity_detail(request, activity_id):
    activity = Activity.objects.get(id=activity_id)
    return render(request, 'activities/detail.html', {'activity': activity})

class ActivityUpdate(LoginRequiredMixin, UpdateView):
    model = Activity
    fields = ['name', 'time', 'description', 'inout']

# class ActivityDelete(LoginRequiredMixin, DeleteView):
#     model = Activity
#     success_url = reverse_lazy('day_detail')

def activity_delete(request, day_id, activity_id):
    activity = Activity.objects.get(id=activity_id)
    # print(activity)
    activity.delete()
    return redirect('day_detail', day_id)

@login_required
def add_photo(request, trip_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file: 
        s3 = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY, aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, S3_BUCKET, key)
            url = f'{S3_BASE_URL}{S3_BUCKET}/{key}'
            photo = Photo(url=url, trip_id=trip_id)
            photo.save()
        except Exception as error:
            print('Error uploading photo', error)
            return redirect('detail', trip_id=trip_id)

    return redirect('trip_detail', trip_id=trip_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('trip_index')
        else:
            error_message = 'Invalid sign up, try again'

    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/trips/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
    <h1>Trip to {{ trip.name }} starting on {{ trip.start }}</h1>
    <hr>
    <div class="columns">
        <div class="column is-two-thirds">
            <h2>Itinerary:</h2>
            <hr>
            {% for day in trip.day_set.all %}
            
            <div class="card m-3 
            {% if day.date < date_now %} 
                has-background-grey-lighter
            {% elif day.date == date_now %} has-background-primary-light
            {% endif %}
            " style="width: 75%;">
                <header class="card-header" >
                    <p class="card-header-title">Day {{ day.number }} 
                        {% if day.city %} 
                            in {{ day.city }},
                            {% if day.state %} {{ day.state }} 
                                {% else %}
                                {% endif %}
                            {{ day.country }} 
                            {% else %}
                        {% endif %}
                        {% if day.date == date_now %} - Today!
                        {% endif %}
                    </p>
                    <p class="card-header-subtitle m-3">{{ day.date }}</p>
                </header>
                <!-- {% if day.activities.count %}
                    <div class="card-content">
                        {% for activity in day.activities.all %}
                            <p>{{ activity.time }} - {{activity.name}}</p>
                        {% endfor %}
                    </div>
                {% endif %} -->
                <footer class="card-footer">
                    <a href="{% url 'day_detail' day.id %}" class="card-footer-item"><strong>View day details</strong></a>
                </footer>
            </div>
            {% endfor%}
        </div>
        <div class="column">
            <h2>Photos:</h2>
            <hr>
            {% for photo in trip.photo_set.all %}
                <div class="card">
                    <img src="{{photo.url}}" alt="Photo of trip to {{ trip.name }}">
                </div>
                {% empty %}
                    <div class="">No Photos yet</div>
                    <br>
                {% endfor %}
                <div class="box">
                    <form 
                    class="card-panel"
                    action="{% url 'add_photo' trip.id %}"
                    method="POST"
                    enctype="multipart/form-data" 
                    >
                        {% csrf_token %}
                        <input type="file" name="photo-file" />
                        <br/><br/>
                        <input type="submit" class="button" value="Upload Photo">
                    </form>
                </div>
        </div>
    </div>
    <!-- {% for item in weather %}
        {% if item.current %}
        <p>Current temp F: {{ item.current.temp_f }}</p><img src="{{ item.current.condition.icon }}">
        {% else %}
        <p>No weather data</p>
        {% endif %}
    {% endfor %} -->
    <!-- <a href="">Never let the party die!</a> | <a href="">Nothing gold can stay.</a> -->
</div>
{% endblock %}

main_app/templates/trips/index.html
{% extends 'base.html' %}
{% block content %}

    {% if trips %}
    {% for trip in trips %}
        <div class="card m-3 " style="width: 75%;">
            <header class="card-header" >
                <span class="card-header-title">Trip to {{ trip.name }}</a></span>
                <span class="card-header-subtitle m-3">Start date: <strong>{{ trip.start }} </strong></span>
            </header>
            <!-- <div class="card-content">
                
            </div> -->
            <footer class="card-footer">
                <a href="{% url 'trip_detail' trip.id %}" class="card-footer-item"><strong>View trip</strong></a>
                <a href="{% url 'trip_delete' trip.id %}" class="card-footer-item"><strong>Cancel trip</strong></a>
            </footer>
        </div>
    {% endfor %}
    {% else %}
    <p>No trips yet! Care to <a href="{% url 'trip_create' %}">Add one</a>?</p>
    {% endif %}
{% endblock %}